# Generated by Django 4.0.6 on 2022-09-06 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_contract_end_date_contract_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='ref_no',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Reference Number'),
        ),
    ]
