# Generated by Django 4.0.6 on 2022-09-06 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_contract_ref_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='payment_made',
            field=models.BooleanField(default=False, verbose_name='Contract payment made'),
        ),
    ]
