# Generated by Django 4.0.6 on 2022-09-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0011_remove_user_username_ar_remove_user_username_de_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportprofile',
            name='responses',
            field=models.IntegerField(default=0, verbose_name='Responses to clients'),
        ),
    ]
