#!/usr/bin/env bash

PROJECT_DIR=/home/$USER/B2B-Ecommerce-Platform

apt-get update -y

# install required software
apt-get install nginx -x
apt-get install python3-pip python3-dev libpq-dev postgresql postgresql-contrib nginx

# set up django project
cd $PROJECT_DIR
python3 -m venv venv
source ./venv/bin/activate
python -m pip install -r ./requirements.txt
python -m pip install django gunicorn psycopg2

# create gunicorn service
touch /etc/systemd/system/gunicorn.service
echo "
[Unit]
Description=gunicorn daemon
After=network.target

[Service]
User=$USER
Group=www-data
WorkingDirectory=$PROJECT_DIR
ExecStart=$PROJECT_DIR/venn/bin/gunicorn --access-logfile - --workers 3 --bind unix:$PROJECT_DIR/myproject.sock core.wsgi:application

[Install]
WantedBy=multi-user.target
" > /etc/systemd/system/gunicorn.service

sudo systemctl start gunicorn
sudo systemctl enable gunicorn

# write nginx conf file
touch b2b
echo "
server{
    listen 80 default_server;
    listen [::]:80 default_server;

    # server_name mugisa.tech

    location = /favicon.ico { access_log off; log_not_found off; }
    location /static/ {
        root $PROJECT_DIR;
    }
    location /media/ {
        root $PROJECT_DIR;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:$PROJECT_DIR/myproject.sock;
    }
}
" > b2b
mv b2b /etc/nginx/sites-available/default

sudo ln -s /etc/nginx/sites-available/b2b /etc/nginx/sites-enabled
nginx -t
service nginx restart
ufw allow 'Nginx Full'