#!/usr/bin/env bash

PROJECT_DIR=/home/B2B-Ecommerce-Platform

apt-get update -y

# install required software
apt-get install -y python3-pip python3-dev libpq-dev postgresql postgresql-contrib nginx


# create db
# user is prompted for db name
echo "Enter Database Name: "
read dbName

echo "Enter Database User: "
read dbUser

if psql -lqt | cut -d \| -f 1 | grep -qw "$dbName"; then
  echo "Database '$DB_NAME' already exists. Exiting."
  exit 1
fi

psql -U $dbUser -d $dbName -c '\d'



# set up django project
# Install pkg-config
sudo apt-get install pkg-config
# Install the development files for cairo
sudo apt-get install libcairo2-dev

cd $PROJECT_DIR
apt install python3.8-venv
python3 -m venv $PROJECT_DIR/venv
source $PROJECT_DIR/venv/bin/activate
python -m pip install -r $PROJECT_DIR/requirements.txt

apt-get install python3-dev libpq-dev
python -m pip install psycopg2-binary
python -m pip install --upgrade setuptools wheel
python -m pip install django gunicorn

# create gunicorn service
touch /etc/systemd/system/gunicorn.service
echo "
[Unit]
Description=gunicorn daemon
After=network.target


user=$1
[Service]
user=$USER
Group=www-data
WorkingDirectory=$PROJECT_DIR
ExecStart=$PROJECT_DIR/venv/bin/gunicorn --access-logfile - --workers 3 --bind unix:$PROJECT_DIR/myproject.sock core.wsgi:application


user=$1
[Install]
WantedBy=multi-user.target
" > /etc/systemd/system/gunicorn.service

sudo systemctl start gunicorn
sudo systemctl enable gunicorn
sudo systemctl daemon-reload


apt-get install nginx -y
# write nginx conf file
echo "
server{
    listen 80 default_server;
    listen [::]:80 default_server;

    # server_name mugisa.tech

    location = /favicon.ico { access_log off; log_clearnot_found off; }
    location /static/ {
        root $PROJECT_DIR;
    }
    location /media/ {
        root $PROJECT_DIR;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:$PROJECT_DIR/myproject.sock;
    }
}
" > default
mv b2b /etc/nginx/sites-available/default

sudo ln -s /etc/nginx/sites-available/b2b /etc/nginx/sites-enabled
nginx -t
service nginx restart
ufw allow 'Nginx Full'