# Generated by Django 4.1 on 2022-08-26 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                blank=True,
                max_length=200,
                null=True,
                unique=True,
                verbose_name="Safe Url",
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="slug",
            field=models.SlugField(
                blank=True,
                max_length=200,
                null=True,
                unique=True,
                verbose_name="Safe Url",
            ),
        ),
        migrations.AlterField(
            model_name="productsubcategory",
            name="slug",
            field=models.SlugField(
                blank=True,
                max_length=200,
                null=True,
                unique=True,
                verbose_name="Safe Url",
            ),
        ),
        migrations.AlterField(
            model_name="store",
            name="slug",
            field=models.SlugField(
                blank=True,
                max_length=200,
                null=True,
                unique=True,
                verbose_name="Safe Url",
            ),
        ),
    ]
