# Generated by Django 4.0 on 2023-12-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_complete',
            field=models.BooleanField(default=True, verbose_name='Completed'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_verified',
            field=models.BooleanField(default=True, verbose_name='Verified by Admin'),
        ),
        migrations.AlterField(
            model_name='store',
            name='is_verified',
            field=models.BooleanField(default=True, verbose_name='Verified by Admin'),
        ),
    ]
