# Generated by Django 4.0.6 on 2022-09-05 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import manager.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth_app', '0012_alter_supportprofile_responses'),
        ('manager', '0008_userrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceimage',
            name='image',
            field=models.ImageField(upload_to=manager.models.get_file_path, verbose_name='Service Image'),
        ),
        migrations.AlterField(
            model_name='showroom',
            name='image',
            field=models.ImageField(default='test/django.png', upload_to=manager.models.get_file_path, verbose_name='Image'),
        ),
        migrations.CreateModel(
            name='Chatroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomname', models.CharField(max_length=256, unique=True, verbose_name='Chatroom Name')),
                ('chatfile', models.FileField(blank=True, null=True, upload_to=manager.models.get_file_path, verbose_name='Chat file')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Chat Closed')),
                ('is_handled', models.BooleanField(default=False, verbose_name='Chat handled')),
                ('created_on', models.DateField(default=django.utils.timezone.now, verbose_name='Created on')),
                ('support', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.supportprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
