# Generated by Django 4.0.6 on 2022-09-05 15:40

from django.db import migrations, models
import manager.models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_alter_serviceimage_image_alter_showroom_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='chatfile',
            field=models.FileField(auto_created=True, upload_to=manager.models.get_chat_file_path, verbose_name='Chat file'),
        ),
    ]
