# Generated by Django 4.0.6 on 2022-09-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_alter_chatroom_chatfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='chatfile',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='chatfilepath',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Chat filepath'),
        ),
    ]
